language: php
php:
  - 7.2
  - 7.3

sudo: required

services:
  - docker

before_isntall:
  - echo 'extension="yaml.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - docker run --name acdh-repo -p 80:8080 -d zozlak/acdh-repo
  - sleep 30
  - "sed -i -e 's|urlBase:.*|urlBase: http://127.0.0.1|g' tests/config.yaml"
  - composer update

